version: "3.8"
services:
  app:  # container 1
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-php
    image: v3ronez/php_8.1_nginx
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-php
  nginx: #container 2
    image: nginx:latest
    container_name: app-nginx
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php

networks:
  app-php:
    driver: bridge
